CLASS zbp_i_fi_group_gj DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_fi_group_gj.

PUBLIC SECTION.
protected section.
private section.


ENDCLASS.



CLASS ZBP_I_FI_GROUP_GJ IMPLEMENTATION.
ENDCLASS.
